apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: chatting-alarm-frontend
  namespace: chatting-alarm
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: chatting-alarm-frontend
