apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: chatting-alarm-backend-secrets
  namespace: chatting-alarm
spec:
  provider: aws

  # false이면 기존에 만든 IRSA ServiceAccount를 사용합니다.
  parameters:
    usePodIdentity: "false"
    region: ap-northeast-2

    objects: |
      - objectName: "chatting-alarm/dev/backend"
        objectType: "secretsmanager"
        jmesPath:
          - path: "GOOGLE_CLIENT_ID"
            objectAlias: "google_client_id"
          - path: "GOOGLE_CLIENT_SECRET"
            objectAlias: "google_client_secret"
          - path: "KAKAO_CLIENT_ID"
            objectAlias: "kakao_client_id"
          - path: "KAKAO_CLIENT_SECRET"
            objectAlias: "kakao_client_secret"
          - path: "NAVER_CLIENT_ID"
            objectAlias: "naver_client_id"
          - path: "NAVER_CLIENT_SECRET"
            objectAlias: "naver_client_secret"

      - objectName: "${RDS_MASTER_SECRET_ARN}"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "db_username"
          - path: "password"
            objectAlias: "db_password"

  secretObjects:
    - secretName: chatting-alarm-backend-secrets
      type: Opaque
      data:
        - objectName: "google_client_id"
          key: GOOGLE_CLIENT_ID

        - objectName: "google_client_secret"
          key: GOOGLE_CLIENT_SECRET

        - objectName: "kakao_client_id"
          key: KAKAO_CLIENT_ID

        - objectName: "kakao_client_secret"
          key: KAKAO_CLIENT_SECRET

        - objectName: "naver_client_id"
          key: NAVER_CLIENT_ID

        - objectName: "naver_client_secret"
          key: NAVER_CLIENT_SECRET

        - objectName: "db_username"
          key: SPRING_DATASOURCE_USERNAME

        - objectName: "db_password"
          key: SPRING_DATASOURCE_PASSWORD
